
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.jorgearias.cl"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: "UA-10005907-9"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "es"
author: "Jorge Arias"
title: "{ Jorge Arias }"
description: "Jorge Arias, estudiante de Ingeniería Civil en Informática y desarrollador informático."
keywords: "jorge, arias, leal, osvaldo, jorge arias, jorge arias leal, ingeniería, informática, informático"
#favicon: "/img/favicon.ico"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

# me-img: "/img/me.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/joariasl.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "jorgearias"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/nisum.png"
    date: "Diciembre 2018 - Febrero 2020"
    description: "DevOps y SRE para Scotiabank @ <a href=\"http://www.nisumlatam.com/\" target=\"_blank\">Nisum</a>"
  - image: "/img/timeline/vacasa.png"
    date: "Enero 2018 - Diciembre 2018"
    description: "Software Developer - Full Stack and DevOps en @ <a href=\"http://www.vacasa.com/\" target=\"_blank\">Vacasa</a>"
  - image: "/img/timeline/everis.png"
    date: "Enero 2016 - Diciembre 2017"
    description: "Consultor informático en @ <a href=\"http://www.everis.com/\" target=\"_blank\">everis Centers Chile</a>"
  - image: "/img/timeline/uct.jpg"
    date: "Marzo 2015 - Abril 2015"
    description: "Gestor y desarrollador de Software en @ <a href=\"http://www.uct.cl/\" target=\"_blank\">Universidad Católica de Temuco</a>"
  - image: "/img/timeline/sssi.jpg"
    date: "2014 - 2015"
    description: "Desarrollador de Sistemas en @ <a href=\"http://www.sanisidrosa.cl/\" target=\"_blank\">Aguas San Isidro</a>"
  - image: "/img/timeline/uct.jpg"
    date: "Febrero 2014 - Junio 2014"
    description: "Desarrollador de Sistemas en @ <a href=\"http://www.uct.cl/\" target=\"_blank\">Universidad Católica de Temuco</a>"
  - image: "/img/timeline/zp.png"
    date: "Febrero 2010 - Junio 2013"
    description: "Webmaster y creador de @ <a href=\"https://youtu.be/qitZpMZQfek\" target=\"_blank\">ZettaPremium</a>"
  - image: "/img/timeline/uct.jpg"
    date: "2008 - 2015"
    description: "Estudiante de Ingeniería Civil en Informática en @ <a href=\"http://www.uct.cl/\" target=\"_blank\">Universidad Católica de Temuco</a>"

# First image of the Timeline

timeline-img: "/img/me.jpg"

###########
# Contact #
###########

email: "mail@jorgearias.cl"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/joariasl"
  - title: "facebook"
    url: "https://www.facebook.com/ZettaOne"
  - title: "twitter"
    url: "https://twitter.com/ZettaOne"
  - title: "instagram"
    url: "https://www.instagram.com/zettaone"
  - title: "youtube"
    url: "https://www.youtube.com/user/JorgeAriasL"
  - title: "github"
    url: "https://github.com/joariasl"
  - title: "tv"
    url: "https://www.livecoding.tv/zettaone/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: joariasl
keybase-in-social: True
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Acerca de: 'about'
  Twitter Timeline: 'twitter-timeline'
  Blog: 'latest-post'
  Carrera: 'timeline'
  Contacto: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
