# Site settings

url: "http://www.jorgearias.cl/"
title: "{ Jorge Arias }"
description: "Jorge Arias, estudiante de Ingeniería Civil en Informática y desarrollador informático."
keywords: "jorge, arias, jorge arias, ingeniería"
#favicon: "/img/favicon.ico"
#black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-10005907-9"
disqus-shortname: False

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Acerca de: 'About'
#  Blog: 'blog'
#  Career: 'career'
  Contacto: 'Contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/microsoft.jpg"
    date: "September 2014 - Today"
    description: "Software Engineer @ Microsoft Development Center Norway, working @ the <a href=\"http://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"
  - image: "/img/career/uoa.jpg"
    date: "October 2012 - August 2014"
    description: "Master studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Software Engineering + <a href=\"http://scholar.google.com/citations?user=UtV6LFYAAAAJ&amp;hl=en&amp;oi=ao\" target=\"_blank\">Machine Learning researcher</a> @ <a href=\"http://kddlab.di.uoa.gr\" target=\"_blank\">KDD</a> lab"
  - image: "/img/career/cern.jpg"
    date: "October 2011 - September 2012"
    description: "Security researcher @ <a href=\"http://www.cern.ch\" target=\"_blank\">CERN</a>, developed linux kernel extensions to prevent cyber attacks"
  - image: "/img/career/writeright.jpg"
    date: "August 2011 - Today"
    description: "Released <a href=\"https://play.google.com/store/apps/details?id=panos.sakkos.softkeyboard.writeright\" target=\"_blank\">WriteRight</a>, an adaptive S/W keyboard for Android devices, which  shrinks the unlikely keys to tap next. Currently it holds &gt; 9,000 downloads"
  - image: "/img/career/pwnmail.jpg"
    date: "June 2010 - November 2010"
    description: "Released <a href=\"https://www.google.com/search?q=pwn+mail\" target=\"_blank\">Pwn Mail</a>, an iPhone app for spoofing emails. It served &gt; 260,000 emails but it was discontinued after a legal threat by <strike>Steve Jobs</strike> a secretary of Steve Jobs"
  - image: "/img/career/uoa.jpg"
    date: "October 2007 - September 2011"
    description: "Bachelor studies @ <a href=\"http://www.di.uoa.gr/eng\" target=\"_blank\">Department of Informatics and Telecommunications</a> on Computer Science and Telecomunications"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
#  - title: "rss"
#    url: "/feed.xml"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/joariasl"
  - title: "twitter"
    url: "https://twitter.com/ZettaOne"
  - title: "github"
    url: "https://github.com/joariasl"
#  - title: "youtube"
#    url: "http://youtube.com/c/PanosSakkos"
#  - title: "soundcloud"
#    url: "https://soundcloud.com/psakkos/"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
#exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", "blog", "career"]
